### ISSUE TITLE
Causing error on Writting kt file [ command :w ]

### ISSUE THREAD

**Issue by blackmo18** [udalov/kotlin-vim#18]
This may not be an issue but a configurations error instead, I'm new to vim, I already searched for related solutions to my issue but I find none. I directed here to find some answers.

```
Error detected while processing function <SNR>58_BufWritePostHook[3]..<SNR>58_UpdateErrors[8]..<SNR>58_CacheErrors[27]
..197[1]..196[3]..SyntaxCheckers_kotlin_kotlinc_GetLocList:
line   22:
E117: Unknown function: syntastic#util#tmpdir
E15: Invalid expression: syntastic#util#tmpdir()
Error detected while processing function <SNR>58_BufWritePostHook[3]..<SNR>58_UpdateErrors[8]..<SNR>58_CacheErrors:
line   27:
E170: Missing :endfor
Error detected while processing function <SNR>58_BufWritePostHook[3]..<SNR>58_UpdateErrors:
line    8:
E171: Missing :endif
```

**Comment by udalov** [comment]
Do you use [Syntastic](https://github.com/vim-syntastic/syntastic), and if yes, what version do you have? If you don't removing `syntax_checkers/kotlin/kotlinc.vim` could help.

Also, could you please paste the output of `vim --version`?

**Comment by blackmo18** [comment]
Hello udalov,
it seems that the problem is an outdated sytastic plugin, I just updated it to the latest version and error is gone. thanks a lot, I enjoyed your plugin.
