### ISSUE TITLE
incorrectly highlights "impl" in import statements

### ISSUE THREAD

**Issue by CoffeeVector** [udalov/kotlin-vim#19]
![image](https://user-images.githubusercontent.com/16787459/47262863-54f90400-d4a8-11e8-99e8-46f5478599e8.png)

**Comment by udalov** [comment]
Thanks for the report. I've fixed this for `header`/`impl` by removing these modifiers (they were replaced with `expect`/`actual` a long ago), but in general it's very difficult to avoid these situations in a regex-based parser. Many other keywords (`get` is one of the most popular) are highlighted where they shouldn't.
