### ISSUE TITLE
send to upstream Vim

### ISSUE THREAD

**Issue by justinmk** [udalov/kotlin-vim#20]
Vim 8.1 does not detect `*.kt` nor `*.kts` files as kotlin.  

Would you consider sending this plugin upstream to https://github.com/vim/vim/ ? All that's needed is for you (the author) to create an issue at https://github.com/vim/vim/ , point to this repo and say that you are the author and you would like it to be included.

**Comment by arturdryomov** [comment]
@justinmk, @udalov, is there a particular reason why this issue was closed? Sounds like a good idea to me.

**Comment by justinmk** [comment]
@arturdryomov I closed it because there apparently wasn't any interest. Sending files upstream is simply a matter of emailing the files to Bram.
