### ISSUE TITLE
Can the grammar color be more beautiful?

### ISSUE THREAD

**Issue by luhuanxml** [udalov/kotlin-vim#27]
Can the grammar color be more beautiful?……^_^

**Comment by udalov** [comment]
Could you please explain what do you mean? If you're talking about the actual colors displayed, it's not a job of a syntax plugin to set fixed colors for code elements; syntax plugins are only assigning groups (such as "operators", "keywords", "string literals" etc.). Groups are then colored by a color scheme, which is installed separately and is completely independent of the syntax plugin. Maybe you're looking for a color scheme instead? (E.g. see https://github.com/rafi/awesome-vim-colorschemes)
