### ISSUE TITLE
Could the syntax files be bundled with vim?

### ISSUE THREAD

**Issue by dbarnett** [udalov/kotlin-vim#39]
It would be great if vim could give you basic Kotlin syntax highlighting out-of-the-box.  Any interest in sending a patch to add syntax into https://github.com/vim/vim/tree/master/runtime/syntax?

**Comment by udalov** [comment]
Sorry for slow reaction on this topic. Indeed, this can be included in the vim runtime. I'll try it.

**Comment by flwyd** [comment]
Has any progress been made on upstreaming the Kotlin syntax into the vim runtime?

**Comment by dkearns** [comment]
@udalov, I've just added vim/vim#13110.

**Comment by udalov** [comment]
@dkearns Thank you!
