### ISSUE TITLE
how kotlin_builtins work

### ISSUE THREAD

**Issue by rockstore** [udalov/kotlin-vim#43]
hello Alexander Udalov， readlly sorry to bother you。I am a newer to kotlin。Recentlly, i am using kotlin in my android project。After packaging my apk file，i found many xx.kotlin_builtins files，i try to figure out how thoses files are generated and how they works，however，information is not enough, just found this url (https://stackoverflow.com/questions/41052868/what-are-kotlin-builtins-files-and-can-i-omit-them-from-my-uberjars/41073782#41073782) , but that url does not make me clear.
Three questions are really taxing my brain：1. how xx.kotlin_builtins files generated  2. how xx.kotlin_builtins files work at runtime 3. are xx.kotlin_builtins files necessary in my apk file？how can i determin which xx.kotlin_builtins file could be deleted？Appreciate that you can provide some docs or answers , eagerly awaiting your response，really thanks!

**Comment by udalov** [comment]
This is not relevant to kotlin-vim and I think I answered it already on the page mentioned above.
