### ISSUE TITLE
Autoindentations: Ignoring comments option's leading spaces.

### ISSUE THREAD

**Issue by CrystalLord** [udalov/kotlin-vim#7]
I've come across a bug in the `indent/kotlin.vim` file. The way it currently handles indentations does not account for C style/Javadoc comments like so:

```kotlin
/**
 * Comment
 * Stuff
 */
fun doSomething(): Int {
    
}
```

**The problem:**

When using the `formatoptions` `r` flag, Vim allows auto placement of comment blocks with a return line. For example, in normal Java, this will look like:

```java
/**
```
Then pressing enter will give:

```java
/**
 *
```

With the default configuration of the `comments` option in Vim. Kotlin's current indentation vim script ignores these settings, and places:

```kotlin
/**
*
```

This cannot be fixed unless the indentation script is modified. My current work around has been to remove the indentation script.

**Comment by udalov** [comment]
Thanks for the report, I think I've fixed it, please check!

**Comment by CrystalLord** [comment]
Fixed! Thank you!
